config/routes.rb
# the routes to our app
Rails.application.routes.draw do
  # get all the task
  get '/tasks', to: 'tasks#index', as: :tasks

  # create new task
  get '/tasks/new', to: 'tasks#new', as: :new_task
  post '/tasks', to: 'tasks#create'

  # update a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # display 1 task
  get '/tasks/:id', to: 'tasks#show', as: :task

  # delete task
  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # get all the tasks form the database
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>This works</h1>
<h1><%= @task.title %></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit("Edit task") %>
<% end %>

app/views/tasks/index.html.erb
<h1>The list of Tasks</h1>
<%= link_to 'Create new Task', new_task_path   %>
<ul>
  <% @tasks.each do |task| %>
    <li> <%= link_to task.title, task_path(task) %> <%= link_to "edit", edit_task_path(task)  %> <%= link_to "delete", destroy_path(task), method: :delete, data: { confirm: "Are you sure?" }  %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>This works</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit("Create Task") %>
<% end %>

<p><%= @task %></p>

app/views/tasks/show.html.erb
<h1>Task: <%= @task.title %></h1>



<h3> -<%= @task.details %></h3>
<h3> - <%= @task.completed %></h3>


<%= link_to "List ", tasks_path %>